# cloudbuild.yaml — builds the Dockerfile, pushes to GCR, and deploys to Cloud Run
# Substitutions can be overridden when running `gcloud builds submit`.
substitutions:
  _SERVICE_NAME: "live-talk-app2"
  _REGION: "us-central1"
  _IMAGE: "live-talk-app2"

options:
  substitutionOption: ALLOW_LOOSE

steps:
# 1) Build the Docker image
- name: "gcr.io/cloud-builders/docker"
  args:
    - "build"
    - "-t"
    - "gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA"
    - "."

# 2) Push the image to Container Registry (GCR)
- name: "gcr.io/cloud-builders/docker"
  args:
    - "push"
    - "gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA"

# 3) Deploy to Cloud Run using gcloud
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      gcloud run deploy "${_SERVICE_NAME}" \
        --image="gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA" \
        --region="${_REGION}" \
        --platform=managed \
        --project="$PROJECT_ID" \
        --allow-unauthenticated

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE}:$SHORT_SHA"